title       : EDIL Fimer - Cosenza
description : Progetta, arreda e decora con stile i tuoi spazi
url         :
  production    : https://www.edilfimer.it
  #development   : https://test.edilfimer.it
  development   : https://edilfimer.gasparesganga.com
author      : 
  name  : Online In 123
  url   : https://onlinein123.com

markdown        : kramdown
kramdown        :
  input : GFM
highlighter     : rouge

include :
  - .htaccess
  - _pages

exclude :
  - .asset-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

gems :
  - jekyll-assets
  - autoprefixer-rails
  - uglifier
  - font-awesome-sass
  - mini_magick

assets : 
  sources       : [_assets, _assets/node_modules/slick-carousel/slick]
  precompile    : []
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : true
  gzip          : false
  defaults      :
    js      : { integrity: true }
    css     : { integrity: true }
    img     : { integrity: true }
  caching       :
    path    : ".jekyll-cache/assets"
    type    : file
    enabled : true
  plugins       :
    css     : { autoprefixer: {}}