title           : EDIL Fimer - Cosenza
description     : Progetta, arreda e decora con stile i tuoi spazi
author          : https://xxxxxxxxxx.com
#production_url  : https://www.edilfimer.it
production_url  : https://edilfimer.gasparesganga.com
development_url : https://test.edilfimer.it

markdown        : kramdown
kramdown        :
  input     : GFM
highlighter     : rouge

include :
  - .htaccess
  - _pages

exclude :
  - browserslist
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

gems :
  - jekyll-assets
  - autoprefixer-rails
  - uglifier
  - font-awesome-sass
  - mini_magick

assets : 
  sources   : [_assets]
  assets    : ["[^_]*|^(?!node_modules\\/).*"]
  #prefix    : /assets
  prefix    : /edilfimer/assets
  cache     : false
  digest    : true
  compress  :
    #js                  : true
    #css                 : true
    js                  : false
    css                 : false
  features:
    automatic_img_size  : false
    automatic_img_alt   : true
    liquid              : false
    integrity           : false